defaults:
    - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug
    - data_augmentation@translation_aug: translation_aug
    - image_encoder: patch_encoder
    - language_encoder: mlp_encoder
    - position_encoding@temporal_position_encoding: sinusoidal_position_encoding
    - policy_head: mlp_head


policy_type: BCViLTPolicy
embed_size: 128

# extra state encoder
extra_state_encoder:
    extra_num_layers: 0
    extra_hidden_size: 128

# encoder
spatial_transformer:
    spatial_transformer_input_size: null
    spatial_transformer_num_layers: 7
    spatial_transformer_num_heads: 8
    spatial_transformer_head_output_size: 120
    spatial_transformer_mlp_hidden_size: 256
    spatial_transformer_dropout: 0.1
    spatial_down_sample: true
    spatial_down_sample_embed_size: 64
    use_language_token: false

# decoder
temporal_transformer:
    transformer_input_size: null
    transformer_num_layers: 4
    transformer_num_heads: 6
    transformer_head_output_size: 64
    transformer_mlp_hidden_size: 256
    transformer_dropout: 0.1
    transformer_max_seq_len: 10
    use_language_token: false

